/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "string_test.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>
#include "s21_string.h"
#include <math.h>
#include <float.h>


// _______________1_memchr___________________

START_TEST(memchr_1) {
char s[20] = "wegrbntrn1";
char ch = 'r';
int size = 10;
ck_assert_pstr_eq(memchr(s,  ch,  size), s21_memchr(s,  ch,  size));}
END_TEST

START_TEST(memchr_2) {
char s[] = "\0";
char ch = 'r';
int size = 0;
ck_assert_pstr_eq(memchr(s,  ch,  size), s21_memchr(s,  ch,  size));}
END_TEST

START_TEST(memchr_3) {
char s[20] = "wegrbntrn2";
char ch = '\0';
int size = 10;
ck_assert_pstr_eq(memchr(s,  ch,  size), s21_memchr(s,  ch,  size));
}
END_TEST

START_TEST(memchr_4) {
char *s = "wegrbntrn3";
char ch = '8';
int size = 0;
ck_assert_pstr_eq(memchr(s,  ch,  size), s21_memchr(s,  ch,  size));
}
END_TEST

START_TEST(memchr_6) {
char *s = "s21_NULL";
char ch = 0;
int size = 10;
ck_assert_pstr_eq(memchr(s,  ch,  size), memchr(s,  ch,  size));
}
END_TEST

START_TEST(memchr_5) {
char s[20] = "wegrbntrn4";
char ch = '8';
int size = 0;
ck_assert_pstr_eq(memchr(s,  ch,  size), s21_memchr(s,  ch,  size));


// _______________2_memcmp____________________
}
END_TEST

START_TEST(memcmp_1) {
char s1[20] = "wegrbntrn5";
char s2[20] = "wegrbntrn5";
int size = 10;
ck_assert_int_eq(memcmp(s1,  s2,  size), s21_memcmp(s1,  s2,  size));
}
END_TEST

START_TEST(memcmp_2) {
char s1[20] = "wegrbntrn6";
char s2[20] = "wegrbntrn6";
int size = 0;
ck_assert_int_eq(memcmp(s1,  s2,  size), s21_memcmp(s1,  s2,  size));
}
END_TEST

START_TEST(memcmp_3) {
char s1[20] = "wegrbntrn7";
char s2[20] = "";
int size = 2;
ck_assert_int_eq(memcmp(s1,  s2,  size), s21_memcmp(s1,  s2,  size));
}
END_TEST

START_TEST(memcmp_4) {
char s1[20] = "weg";
char s2[20] = "WEG";
int size = 3;
ck_assert_int_eq(memcmp(s1,  s2,  size), s21_memcmp(s1,  s2,  size));
}
END_TEST

START_TEST(memcmp_6) {
char *s1 = "\0";
char *s2 = "\0\0";
int size = 1;
ck_assert_int_eq(memcmp(s1,  s2,  size), s21_memcmp(s1,  s2,  size));
}
END_TEST

START_TEST(memcmp_7) {
char *s1 = "\0";
char *s2 = "\0\0";
int size = 0;
ck_assert_int_eq(memcmp(s1,  s2,  size), s21_memcmp(s1,  s2,  size));
}
END_TEST

START_TEST(memcmp_5) {
char s1[20] = "weg";
char s2[20] = "WEG4";
int size = 3;
ck_assert_int_eq(memcmp(s1,  s2,  size), s21_memcmp(s1,  s2,  size));


// _______________3_memcpy____________________(UPDATED)
}
END_TEST

START_TEST(memcpy_1) {
char s1[20] = "Delhi";
char s2[20] = "";
int size = 3;
ck_assert_pstr_eq(memcpy(s1,  s2,  size), s21_memcpy(s1,  s2,  size));
}
END_TEST

START_TEST(memcpy_2) {
char s1[20] = "Delhi";
char s2[20] = "f";
int size = 5;
ck_assert_pstr_eq(memcpy(s1,  s2,  size), s21_memcpy(s1,  s2,  size));
}
END_TEST

START_TEST(memcpy_3) {
char s1[20] = "\0";
char s2[20] = "";
int size = 1;
ck_assert_pstr_eq(memcpy(s1,  s2,  size), s21_memcpy(s1,  s2,  size));
}
END_TEST

START_TEST(memcpy_4) {
char s1[20] = "";
char s2[20] = "";
int size = 0;
ck_assert_pstr_eq(memcpy(s1,  s2,  size), s21_memcpy(s1,  s2,  size));
}
END_TEST

START_TEST(memcpy_5) {
char s1[20] = "\0";
char s2[20] = "\0";
int size = 1;
ck_assert_pstr_eq(memcpy(s1,  s2,  size), s21_memcpy(s1,  s2,  size));


// _______________4_memmove____________________
}
END_TEST

START_TEST(memmove_1) {
char s1[20] = "Delhi";
char s2[20] = "";
int size = 5;
ck_assert_pstr_eq(memmove(s1,  s2,  size), s21_memmove(s1,  s2,  size));
}
END_TEST

START_TEST(memmove_2) {
char s1[20] = "Delhi";
char s2[20] = "f";
int size = 0;
ck_assert_pstr_eq(memmove(s1,  s2,  size), s21_memmove(s1,  s2,  size));
}
END_TEST

START_TEST(memmove_3) {
char s1[20] = "\0";
char s2[20] = "";
int size = 1;
ck_assert_pstr_eq(memmove(s1,  s2,  size), s21_memmove(s1,  s2,  size));
}
END_TEST

START_TEST(memmove_4) {
char s1[20] = "";
char s2[20] = "\0";
int size = 1;
ck_assert_pstr_eq(memmove(s1,  s2,  size), s21_memmove(s1,  s2,  size));
}
END_TEST
START_TEST(memmove_6) {
char s1[20] = "23";
char s2[20] = "34";
int size = 19;
ck_assert_pstr_eq(memmove(s1,  s2,  size), s21_memmove(s1,  s2,  size));
}
END_TEST
START_TEST(memmove_5) {
char s1[20] = "\0";
char s2[20] = "\0";
int size = 0;
ck_assert_pstr_eq(memmove(s1,  s2,  size), s21_memmove(s1,  s2,  size));

// _______________5_memset____________________
}
END_TEST

START_TEST(memset_1) {
char s1[20] = "Delhi";
char s2 = '*';
int size = 2;
ck_assert_pstr_eq(memset(s1,  s2,  size), s21_memset(s1,  s2,  size));
}
END_TEST

START_TEST(memset_2) {
char s1[20] = "Delhi";
char s2 = '\0';
int size = 0;
ck_assert_pstr_eq(memset(s1,  s2,  size), s21_memset(s1,  s2,  size));
}
END_TEST

START_TEST(memset_3) {
char s1[20] = "\0";
char s2 = '=';
int size = 1;
ck_assert_pstr_eq(memset(s1,  s2,  size), s21_memset(s1,  s2,  size));
}
END_TEST

START_TEST(memset_4) {
char s1[20] = "";
char s2 = '=';
int size = 1;
ck_assert_pstr_eq(memset(s1,  s2,  size), s21_memset(s1,  s2,  size));
}
END_TEST

START_TEST(memset_6) {
char *s1 = "\0";
char s2 = '\0';
int size = 0;
ck_assert_pstr_eq(memset(s1,  s2,  size), s21_memset(s1,  s2,  size));
}
END_TEST


START_TEST(memset_5) {
char s1[20] = "tjtyjt";
char s2 = '=';
int size = 5;
ck_assert_pstr_eq(memset(s1,  s2,  size), s21_memset(s1,  s2,  size));


// _______________6_strcat____________________
}
END_TEST

START_TEST(strcat_1) {
char s1[250] = "Initial";
char s2[20] = ",  want to add";
ck_assert_pstr_eq(strcat(s1,  s2), s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcat_2) {
char s1[250] = "Terr";
char s2[20] = "a";
ck_assert_pstr_eq(strcat(s1,  s2), s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcat_3) {
char s1[250] = "Hi\0true";
char s2[20] = " ";
ck_assert_pstr_eq(strcat(s1,  s2), s21_strcat(s1,  s2));
}
END_TEST

START_TEST(strcat_4) {
char s1[250] = "Initial";
char s2[20] = ",  want to add";
ck_assert_pstr_eq(strcat(s1,  s2), s21_strcat(s1,  s2));
}
END_TEST


START_TEST(strcat_5) {
char s1[250] = "\0";
char s2[20] = "\0";
ck_assert_pstr_eq(strcat(s1,  s2), s21_strcat(s1,  s2));


// _______________7_strncat____________________
}
END_TEST

START_TEST(strncat_1) {
char s1[250] = "Initial";
char s2[20] = ",  want to add";
int size = 5;
ck_assert_str_eq(strncat(s1,  s2,  size), s21_strncat(s1,  s2,  size));
}
END_TEST

START_TEST(strncat_2) {
char s1[250] = "";
char s2[20] = ",  want to add";
int size = 0;
ck_assert_str_eq(strncat(s1,  s2,  size), s21_strncat(s1,  s2,  size));
}
END_TEST

START_TEST(strncat_3) {
char s1[250] = "Initial";
char s2[20] = "";
int size = 5;
ck_assert_str_eq(strncat(s1,  s2,  size), s21_strncat(s1,  s2,  size));
}
END_TEST

START_TEST(strncat_4) {
char s1[250] = "Initial";
char s2[20] = ",  ";
int size = 15;
ck_assert_str_eq(strncat(s1,  s2,  size), s21_strncat(s1,  s2,  size));
}
END_TEST


START_TEST(strncat_5) {
char s1[250] = "dfgdfgdf";
char s2[20] = " ";
int size = 1;
ck_assert_str_eq(strncat(s1,  s2,  size), s21_strncat(s1,  s2,  size));


// _______________8_strchr___________________
}
END_TEST

START_TEST(strchr_1) {
char s[20] = "wegrbntrn11";
char ch = 'r';
ck_assert_pstr_eq(strchr(s,  ch), s21_strchr(s,  ch));
}
END_TEST

START_TEST(strchr_2) {
char s[20] = "";
char ch = 'r';
ck_assert_pstr_eq(strchr(s,  ch), s21_strchr(s,  ch));
}
END_TEST

START_TEST(strchr_3) {
char s[20] = "wegrbntrn12";
char ch = '\0';
ck_assert_pstr_eq(strchr(s,  ch), s21_strchr(s,  ch));
}
END_TEST

START_TEST(strchr_4) {
char s[20] = "wegrbntrn13";
char ch = '8';
ck_assert_pstr_eq(strchr(s,  ch), s21_strchr(s,  ch));
}
END_TEST


START_TEST(strchr_5) {
char s[20] = "wegrbntrn14";
char ch = '8';
ck_assert_pstr_eq(strchr(s,  ch), s21_strchr(s,  ch));


// _______________9_strcmp___________________
}
END_TEST

START_TEST(strcmp_1) {
char s1[20] = "qwferty";
char s2[20] = "qwerty1235";
ck_assert_int_eq(strcmp(s1,  s2), s21_strcmp(s1,  s2));
}
END_TEST

START_TEST(strcmp_2) {
char s1[20] = "\0";
char s2[20] = "\0";
ck_assert_int_eq(strcmp(s1,  s2), s21_strcmp(s1,  s2));
}
END_TEST


START_TEST(strcmp_3) {
char s1[20] = "trh";
char s2[20] = "";
int res_s21 = s21_strcmp(s1, s2);
int res_org = strcmp(s1, s2);
if (res_s21 < 0) {
    res_s21 = -1;
} else if (res_s21 > 0) {
    res_s21 = 1;
} else {
    res_s21 = 0;
}
if (res_org < 0) {
    res_org = -1;
} else if (res_org > 0) {
    res_org = 1;
} else {
    res_org = 0;
}
ck_assert_int_eq(res_org, res_s21);
}
END_TEST

START_TEST(strcmp_4) {
char s1[20] = "TEST";
char s2[20] = "TeSti";
int res_s21 = s21_strcmp(s1, s2);
int res_org = strcmp(s1, s2);
if (res_s21 < 0) {
    res_s21 = -1;
} else if (res_s21 > 0) {
    res_s21 = 1;
} else {
    res_s21 = 0;
}
if (res_org < 0) {
    res_org = -1;
} else if (res_org > 0) {
    res_org = 1;
} else {
    res_org = 0;
}
ck_assert_int_eq(res_org, res_s21);}
END_TEST

START_TEST(strcmp_5) {
char s1[20] = "ty";
char s2[20] = "ty";
ck_assert_int_eq(strcmp(s1,  s2), s21_strcmp(s1,  s2));


// _______________10_strncmp___________________
}
END_TEST

START_TEST(strncmp_1) {
char s1[20] = "qwferty";
char s2[20] = "qwerty1235";
int size = 10;
ck_assert_int_eq(strncmp(s1,  s2,  size), s21_strncmp(s1,  s2,  size));
}
END_TEST

START_TEST(strncmp_2) {
char s1[20] = "q";
char s2[20] = "q";
int size = 10;
ck_assert_int_eq(strncmp(s1,  s2,  size), s21_strncmp(s1,  s2,  size));
}
END_TEST

START_TEST(strncmp_6) {
char *s1 = "\0";
char *s2 = "\0\0";
int size = 10;
ck_assert_int_eq(strncmp(s1,  s2,  size), s21_strncmp(s1,  s2,  size));
}
END_TEST

START_TEST(strncmp_3) {
char s1[20] = " fg";
char s2[20] = "fg";
int size = 10;
int res_s21 = s21_strncmp(s1, s2, size);
int res_org = strncmp(s1, s2, size);

if (res_s21 < 0) {
    res_s21 = -1;
} else if (res_s21 > 0) {
    res_s21 = 1;
} else {
    res_s21 = 0;
}

if (res_org < 0) {
    res_org = -1;
} else if (res_org > 0) {
    res_org = 1;
} else {
    res_org = 0;
}

ck_assert_int_eq(res_org, res_s21);
}
END_TEST

START_TEST(strncmp_4) {
char s1[20] = " ";
char s2[20] = " ";
int size = 0;
ck_assert_int_eq(strncmp(s1,  s2,  size), s21_strncmp(s1,  s2,  size));
}
END_TEST

START_TEST(strncmp_5) {
char s1[20] = "123";
char s2[20] = "123";
int size = 10;
ck_assert_int_eq(strncmp(s1,  s2,  size), s21_strncmp(s1,  s2,  size));


// _______________11_strcpy___________________
}
END_TEST

START_TEST(strcpy_1) {
char s1[20] = "Delhi";
char s2[20] = "";
ck_assert_pstr_eq(strcpy(s1,  s2), s21_strcpy(s1,  s2));
}
END_TEST

START_TEST(strcpy_2) {
char s1[20] = "Delhi";
char s2[20] = "f";
ck_assert_pstr_eq(strcpy(s1,  s2), s21_strcpy(s1,  s2));
}
END_TEST


START_TEST(strcpy_3) {
char s1[20] = "\0";
char s2[20] = "";
ck_assert_pstr_eq(strcpy(s1,  s2), s21_strcpy(s1,  s2));
}
END_TEST

START_TEST(strcpy_4) {
char s1[20] = "";
char s2[20] = "";
ck_assert_pstr_eq(strcpy(s1,  s2), s21_strcpy(s1,  s2));
}
END_TEST

START_TEST(strcpy_5) {
char s1[20] = "\0";
char s2[20] = "";
ck_assert_pstr_eq(strcpy(s1,  s2), s21_strcpy(s1,  s2));


// _______________12_strncpy___________________
}
END_TEST

START_TEST(strncpy_1) {
char s1[15] = "y";
char s2[15] = "wegrbntrn15";
int size = 5;
ck_assert_str_eq(strncpy(s1,  s2,  size), s21_strncpy(s1,  s2,  size));
}
END_TEST

START_TEST(strncpy_2) {
char s1[20] = "";
char s2[20] = "wegrbntrn16";
int size = 0;
ck_assert_str_eq(strncpy(s1,  s2,  size), s21_strncpy(s1,  s2,  size));
}
END_TEST


START_TEST(strncpy_3) {
char s1[20] = "";
char s2[20] = "\0";
int size = 1;
ck_assert_str_eq(strncpy(s1,  s2,  size), s21_strncpy(s1,  s2,  size));
}
END_TEST

START_TEST(strncpy_4) {
char s1[20] = "l";
char s2[20] = "wegrbntrn17";
int size = 0;
ck_assert_str_eq(strncpy(s1,  s2,  size), s21_strncpy(s1,  s2,  size));
}
END_TEST

START_TEST(strncpy_5) {
char s1[20] = "";
char s2[20] = "fvf\0fdb";
int size = 1;
ck_assert_str_eq(strncpy(s1,  s2,  size), s21_strncpy(s1,  s2,  size));


// _______________13_strcspn___________________
}
END_TEST

START_TEST(strcspn_1) {
char s1[20] = "dfgshsh";
char s2[20] = "2e";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strcspn_2) {
char s1[20] = "2e";
char s2[20] = "2e";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strcspn_6) {
char *s1 = "\0";
char *s2 = "\0";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strcspn_3) {
char s1[20] = "\0";
char s2[20] = "2e";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strcspn_4) {
char s1[20] = "dfgshsh";
char s2[20] = "\0";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));
}
END_TEST

START_TEST(strcspn_5) {
char s1[20] = "dfgshsh";
char s2[20] = "09";
ck_assert_int_eq(strcspn(s1,  s2), s21_strcspn(s1,  s2));


// _______________14_strerr__________________
}
END_TEST

START_TEST(strerror_1) {
int n = 0;
ck_assert_pstr_eq(strerror(n), s21_strerror(n));
}
END_TEST

START_TEST(strerror_2) {
int n = 107;
ck_assert_pstr_eq(strerror(n), s21_strerror(n));
}
END_TEST

START_TEST(strerror_3) {
int n = 150;
ck_assert_pstr_eq(strerror(n), s21_strerror(n));
}
END_TEST

START_TEST(strerror_4) {
int n = -1;
ck_assert_pstr_eq(strerror(n), s21_strerror(n));
}
END_TEST

START_TEST(strerror_5) {
int n = 15;
ck_assert_pstr_eq(strerror(n), s21_strerror(n));


// _______________15_strlen__________________
}
END_TEST

START_TEST(strlen_1) {
char s1[20]="hello world";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));
}
END_TEST


START_TEST(strlen_2) {
char s1[20]="\0";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));
}
END_TEST

START_TEST(strlen_3) {
char s1[20]=" ";
ck_assert_int_eq(strlen(s1), s21_strlen(s1));


// _______________16_strpbrk_________________
}
END_TEST

START_TEST(strpbrk_1) {
char s1[20] = "wegrbntrn18";
char s2[20] = "r";
ck_assert_pstr_eq(strpbrk(s1,  s2), s21_strpbrk(s1,  s2));
}
END_TEST

START_TEST(strpbrk_2) {
char s1[20] = "weg";
char s2[20] = "r";
ck_assert_pstr_eq(strpbrk(s1,  s2), s21_strpbrk(s1,  s2));
}
END_TEST

START_TEST(strpbrk_6) {
char *s1 = "\0";
char *s2 = "\0";
ck_assert_pstr_eq(strpbrk(s1,  s2), s21_strpbrk(s1,  s2));
}
END_TEST

START_TEST(strpbrk_3) {
char s1[20] = "\0";
char s2[20] = "r";
ck_assert_pstr_eq(strpbrk(s1,  s2), s21_strpbrk(s1,  s2));
}
END_TEST

START_TEST(strpbrk_4) {
char s1[20] = "wegrbntrn19";
char s2[20] = "\0";
ck_assert_pstr_eq(strpbrk(s1,  s2), s21_strpbrk(s1,  s2));


// _______________17_strrchr_________________
}
END_TEST

START_TEST(strrchr_1) {
char s[20] = "wegrbntrn20";
char ch = 'r';
ck_assert_pstr_eq(strrchr(s,  ch), s21_strrchr(s,  ch));
}
END_TEST

START_TEST(strrchr_2) {
char s[1] = "\0";
char ch = 'r';
ck_assert_pstr_eq(strrchr(s,  ch), s21_strrchr(s,  ch));
}
END_TEST

START_TEST(strrchr_6) {
char s[1] = "\0";
char ch = '\0';
ck_assert_pstr_eq(strrchr(s,  ch), s21_strrchr(s,  ch));
}
END_TEST

START_TEST(strrchr_3) {
char s[20] = "wegrbntrn21";
char ch = '\0';
ck_assert_pstr_eq(strrchr(s,  ch), s21_strrchr(s,  ch));
}
END_TEST

START_TEST(strrchr_4) {
char s[5] = "we";
char ch = 'q';
ck_assert_pstr_eq(strrchr(s,  ch), s21_strrchr(s,  ch));


// _______________18_strspn_________________
}
END_TEST

START_TEST(strspn_1) {
char str1[20] = "223351878";
char str2[10] = "12345";
ck_assert_int_eq(strspn(str1,  str2),  s21_strspn(str1,  str2));
}
END_TEST

START_TEST(strspn_2) {
char str1[20] = "223351878";
char str2[10] = "fgdjfh";
ck_assert_int_eq(strspn(str1,  str2),  s21_strspn(str1,  str2));
}
END_TEST

START_TEST(strspn_3) {
char str1[20] = "\0";
char str2[10] = "fgdjfh";
ck_assert_int_eq(strspn(str1,  str2),  s21_strspn(str1,  str2));
}
END_TEST

START_TEST(strspn_4) {
char str1[20] = "dfb";
char str2[10] = "\0vf";
ck_assert_int_eq(strspn(str1,  str2),  s21_strspn(str1,  str2));
}
END_TEST

START_TEST(strspn_6) {
char str1[20] = "\0";
char str2[10] = "\0\0";
ck_assert_int_eq(strspn(str1,  str2),  s21_strspn(str1,  str2));
}
END_TEST

START_TEST(strspn_5) {
char str1[20] = "12";
char str2[10] = "1212121";
ck_assert_int_eq(strspn(str1,  str2),  s21_strspn(str1,  str2));


// _______________19_strstr_________________
}
END_TEST

START_TEST(strstr_1) {
char s1[20] = "wegrbntrn22";
char s2[20] = "egr";
ck_assert_pstr_eq(strstr(s1,  s2), s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strstr_2) {
char s1[20] = " ";
char s2[20] = "  ";
ck_assert_pstr_eq(strstr(s1,  s2), s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strstr_6) {
char s1[20] = "\0";
char s2[20] = "\0";
ck_assert_pstr_eq(strstr(s1,  s2), s21_strstr(s1,  s2));
}
END_TEST


START_TEST(strstr_3) {
char s1[20] = "\0";
char s2[20] = "df";
ck_assert_pstr_eq(strstr(s1,  s2), s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strstr_4) {
char s1[20] = "34t";
char s2[20] = "\0";
ck_assert_pstr_eq(strstr(s1,  s2), s21_strstr(s1,  s2));
}
END_TEST

START_TEST(strstr_5) {
char s1[20] = "w";
char s2[20] = "we";
ck_assert_pstr_eq(strstr(s1,  s2), s21_strstr(s1,  s2));


// _______________20_strtok_________________
}
END_TEST

START_TEST(strtok_1) {
char s[20] = "weg|rbnt|rn";
char ch[20]  = " |";
char *res_org = strtok(s,  ch);
char *res_s21 = s21_strtok(s,  ch);

while(res_org != s21_NULL && res_s21 != s21_NULL) {
    ck_assert_pstr_eq(res_org,  res_s21);
    res_org = strtok(s21_NULL,  ch);
    res_s21 = s21_strtok(s21_NULL,  ch);
    }
}
END_TEST

START_TEST(strtok_2) {
char s[20] = "weg rbn    t|rn";
char ch[20] = " |";
char *res_org = strtok(s,  ch);
char *res_s21 = s21_strtok(s,  ch);

while(res_org != s21_NULL && res_s21 != s21_NULL) {
    ck_assert_pstr_eq(res_org,  res_s21);
    res_org = strtok(s21_NULL,  ch);
    res_s21 = s21_strtok(s21_NULL,  ch);
    }
}
END_TEST

START_TEST(strtok_3) {
char s[20] = "12|";
char ch[20] = " |";
char *res_org = strtok(s,  ch);
char *res_s21 = s21_strtok(s,  ch);

while(res_org != s21_NULL && res_s21 != s21_NULL) {
    ck_assert_pstr_eq(res_org,  res_s21);
    res_org = strtok(s21_NULL,  ch);
    res_s21 = s21_strtok(s21_NULL,  ch);
    }
}
END_TEST

START_TEST(strtok_4) {
char s[20] = "weg|rbnt|rn";
char ch[20] = "\0";
char *res_org = strtok(s,  ch);
char *res_s21 = s21_strtok(s,  ch);

while(res_org != s21_NULL && res_s21 != s21_NULL) {
    ck_assert_pstr_eq(res_org,  res_s21);
    res_org = strtok(s21_NULL,  ch);
    res_s21 = s21_strtok(s21_NULL,  ch);
    }
}
END_TEST

START_TEST(strtok_5) {
char s[20] = "...test/test/test...";
char ch[20] = "./";
char *res_org = strtok(s,  ch);
char *res_s21 = s21_strtok(s,  ch);

while(res_org != s21_NULL && res_s21 != s21_NULL) {
    ck_assert_pstr_eq(res_org,  res_s21);
    res_org = strtok(s21_NULL,  ch);
    res_s21 = s21_strtok(s21_NULL,  ch);
    }


// _______________1_bonus_to_upper_________________
}
END_TEST

START_TEST(to_upper_1) {
char str[] = "wegrbntrn23";
char *res_s21 = s21_to_upper(str);
char res_org[] = "WEGRBNTRN23";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_upper_2) {
char str[] = "WeGrbnTrN";
char *res_s21 = s21_to_upper(str);
ck_assert_pstr_eq(res_s21,  "WEGRBNTRN");
free(res_s21);
}
END_TEST

START_TEST(to_upper_3) {
char str[2] = "\0";
char *res_s21 = s21_to_upper(str);
char res_org[2] = "\0";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_upper_4) {
char str[20] = "  _ wegr3412";
char *res_s21 = s21_to_upper(str);
char res_org[20] = "  _ WEGR3412";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_upper_5) {
char str[20] = "we\0grbntrn";
char *res_s21 = s21_to_upper(str);
char *res_org = "WE";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_upper_6) {
char str[20] = "WE";
char *res_s21 = s21_to_upper(str);
char *res_org = "WE";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_upper_7) {
char str[20] = "123";
char *res_s21 = s21_to_upper(str);
char *res_org = "123";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_upper_8) {
char str[20] = "\0";
char *res_s21 = s21_to_upper(str);
char *res_org = "\0";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);


// _______________2_bonus_to_lower_________________
}
END_TEST

START_TEST(to_lower_1) {
char str[20] = "WEGRBNTRN111";
char *res_s21 = s21_to_lower(str);
char res_org[20] = "wegrbntrn111";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_lower_2) {
char str[20] = "WeGrbnTrN222";
char *res_s21 = s21_to_lower(str);
char res_org[20] = "wegrbntrn222";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_lower_3) {
char str[20] = "";
char *res_s21 = s21_to_lower(str);
char *res_org = "";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_lower_4) {
char str[20] = "  _ WEGR34";
char *res_s21 = s21_to_lower(str);
char *res_org = "  _ wegr34";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_lower_5) {
char str[20] = "WE\0grbntrn";
char *res_s21 = s21_to_lower(str);
char *res_org = "we";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_lower_6) {
char str[20] = "we";
char *res_s21 = s21_to_lower(str);
char *res_org = "we";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(to_lower_7) {
char str[20] = "123";
char *res_s21 = s21_to_lower(str);
char *res_org = "123";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
// _______________3_bonus_insert_______________
}
END_TEST

START_TEST(insert_1) {
char src[] = "0";
char str[] = "1";
s21_size_t start_index = 0;
char *res_s21 = s21_insert(src,  str,  start_index);
char res_org[20] = "10";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(insert_2) {
char src[] = " 023";
char str[] = "1";
s21_size_t start_index = 0;
char *res_s21 = s21_insert(src,  str,  start_index);
char res_org[10] = "1 023";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(insert_4) {
char src[20] = "0123";
char str[20] = "1";
s21_size_t start_index = 7;
char *res_s21 = s21_insert(src,  str,  start_index);
char *res_org = s21_NULL;
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(insert_5) {
char src[20] = "11";
char str[20] = "0";
s21_size_t start_index = 1;
char *res_s21 = s21_insert(src,  str,  start_index);
char res_org[20] = "101";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(insert_6) {
char src[20] = "wdgbbef";
char str[1] = "\0";
s21_size_t start_index = 2;
char *res_s21 = s21_insert(src,  str,  start_index);
char res_org[] = "wdgbbef";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST


// _______________4_bonus_trim_______________

START_TEST(trim_1) {
char src[5] = "f45f";
char trim_chars[5] = "f6";
char *res_s21 = s21_trim(src,  trim_chars);
char res_org[5] = "45";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(trim_2) {
char src[5] = "123";
char trim_chars[5] = "f6";
char *res_s21 = s21_trim(src,  trim_chars);
char res_org[5] = "123";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(trim_3) {
char src[30] = "123u3iui78231";
char trim_chars[10] = "1hg23";
char *res_s21 = s21_trim(src,  trim_chars);
char res_org[20] = "u3iui78";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(trim_4) {
char src[5] = "\0";
char trim_chars[5] = "f6";
char *res_s21 = s21_trim(src,  trim_chars);
char *res_org = "\0";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(trim_5) {
char src[6] = "fg\0fv";
char trim_chars[6] = "f6";
char *res_s21 = s21_trim(src,  trim_chars);
char res_org[5] = "g";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}
END_TEST

START_TEST(trim_7) {
char src[] = "qqq";
char *trim_chars = "q";
char *res_s21 = s21_trim(src, trim_chars);
char *res_org = "\0";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}

START_TEST(trim_10) {
char src[] = "\0";
char *trim_chars = "\0";
char *res_s21 = s21_trim(src, trim_chars);
char *res_org = "\0";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}

START_TEST(trim_8) {
char src[] = "qqq    v   ";
char *trim_chars = s21_NULL;
char *res_s21 = s21_trim(src,  trim_chars);
char res_org[] = "qqq    v";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
}

END_TEST
START_TEST(trim_6) {
char src[10] = "/=f45f";
char trim_chars[5] = "f";
char *res_s21 = s21_trim(src,  trim_chars);
char res_org[10] = "/=f45";
ck_assert_pstr_eq(res_s21,  res_org);
free(res_s21);
// _______________sprintf_e_________________
}
END_TEST

START_TEST(sprintf_1) {
char format[50] = "|%-30.6f|%-30.6f|%+-030.6f|%-030.6f|";
char destination_org[200];
char destination_s21[200];
float a = 1231.1231;
float b = 1231.1231;
float c = 0.121;
float d = 0;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_s21,  res_org);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_e2) {
char format[50] = "|%-30.6f|%-30.6f|%+-030.6f|%-030.6f|";
char destination_s21[200];
char destination_org[200];
float a = 1231.1231;
float b = -1231.1231;
float c = 1.86;
float d = 0;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_e3) {
char format[] = "|%0.6f|%-00.0001f|%+-20f|";
char destination_s21[200];
char destination_org[200];
float a = 121251;
float b = -1231.1231;
float c = 0.121;
float d = 0;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_e4) {
char format[] = "|%0.6f|%+0000.00000f|%+-90f|";
char destination_s21[200];
char destination_org[200];
float a = 123111.1231;
float b = -12381.131;
float c = -0.121;
float d = 0;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_d3) {
char format[50] = "|%-010.20d|%+010.20d|%-010.20d|%+010.20d|";
char destination_s21[200];
char destination_org[200];
int a = -1231;
int b = 1231231;
int c = -81;
int d = -0;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST



START_TEST(sprintf_d4) {
char format[50] = "|% 010.3d|% 010.3d|% 010.3d|% 010.3d|";
char destination_s21[200];
char destination_org[200];
int a = 81;
int b = -1231231;
int c = -81;
int d = 0;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_d5) {
char format[50] = "|%d|%d|%d|%d|";
char destination_s21[200];
char destination_org[200];
int a = 856782;
int b = -58552;
int c = 0;
int d = 0;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

// _______________sprintf_f_________________

START_TEST(sprintf_f1) {
char format[50] = "|%f|%f|%f|%f|";
char destination_s21[200];
char destination_org[200];
float a = 4;
float b = -5755;
float c = 44;
float d = 0;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_f2) {
char format[50] = "|%+11f|%11f|%-11f|%+-11f|";
char destination_s21[200];
char destination_org[200];
float a = 4.7578;
float b = -5755.57;
float c = -44;
float d = 4580;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_f3) {
char format[50] = "|% 20.5f|%-020.5f|%+20.5f|%-020.5f|";
char destination_s21[200];
char destination_org[200];
float a = 42114;
float b = -5755;
float c = 78744;
float d = -0.005544;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_f4) {
char format[50] = "|% 20.5f|%-020.5f|%+20.5f|%-20.5f|";
char destination_s21[200];
char destination_org[200];
float a = 41121.3554774;
float b = -5755.22440057533;
float c = 0;
float d = -0.0000005544;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_c1) {
char format[50] = "|%-10.3c|%-30.10c|% 30.20c|%40.15c|";
char destination_s21[200];
char destination_org[200];
char a = '4';
char b = '-';
char c = 'j';
char d = ' ';
char res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
char res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_c2) {
char format[50] = "|%c|%c|% 30.20c|%40c|";
char destination_s21[200];
char destination_org[200];
char a = '4';
char b = '-';
char c = 'j';
char d = ' ';
char res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
char res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_c3) {
char format[50] = "|%c|%c|%c|%c|";
char destination_s21[200];
char destination_org[200];
char a = '\'';
char b = 'p';
char c = '\"';
char d = ' ';
char res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
char res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);


// _______________sprintf_s_________________
}
END_TEST

START_TEST(sprintf_s1) {
char format[50] = "|% 20.10s|%-020.10s|%+20.10s|%-020.10s|";
char destination_s21[200];
char destination_org[200];
char a[] = "hello world";
char b[] = "     ";
char c[] = "'hi'";
char d[] = " ";
char res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
char res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_s2) {
char format[50] = "|% 20.10s|%-020.10s|%+20.10s|%-020.10s|";
char destination_s21[200];
char destination_org[200];
char a[] = "hello \\ world \\";
char b[] = "\\";
char c[] = "'hi'";
char d[] = "lol\0 lol lol";
char res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
char res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_s3) {
char format[50] = "|%s|%s|%s|%s|";
char destination_s21[200];
char destination_org[200];
char a[] = "hello \\ WORLD \\";
char b[] = " NoNoYES";
char c[] = "\"";
char d[] = "lol\0 World  lol";
char res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
char res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_s4) {
char format[50] = "|%2s|%2s|%2s|%2s|";
char destination_s21[200];
char destination_org[200];
char a[] = "hello \\ WORLD \\";
char b[] = " NoNoYES";
char c[] = "\"";
char d[] = "lol\0 World  lol";
char res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
char res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_s5) {
char format[50] = "|%- +33.2s|%+- +3.2s|%+- +3.2s|%-33.0s";
char destination_s21[200];
char destination_org[200];
char *a = s21_NULL;
char b[] = "\0";
char c[] = " \0";
char d[] = "\0\0";
char res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
char res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);

// _______________sscanf_c_________________
}
END_TEST

START_TEST(sprintf_u1) {
char format[50] = "|% 20.5u|%+20.5u|%- 4.5u|%-+20.5u|";
char destination_s21[200];
char destination_org[200];
unsigned int a = 0,  b = 123,  c = 23423,  d = 23423;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_u2) {
char format[50] = "|% 20.5lu|%+20.5lu|%- 4.5lu|%-+20.5lu|";
char destination_s21[200];
char destination_org[200];
unsigned long int a = 0,  b = 123,  c = 23423,  d = 23423;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_u3) {
char format[50] = "|% 20.5hu|%+20.5hu|%- 4.5hu|%-+20.5hu|";
char destination_s21[200];
char destination_org[200];
unsigned short int a = 0,  b = 123,  c = 23423,  d = 23423;
int res_org = sprintf(destination_org,  format,  a,  b,  c,  d);
int res_s21 = s21_sprintf(destination_s21,  format,  a,  b,  c,  d);
ck_assert_int_eq(res_org,  res_s21);
ck_assert_pstr_eq(destination_s21,  destination_org);


// _______________sprintf_Le_________________
}
END_TEST

START_TEST(sprintf_hd1) {
short int a_hd = 0,  b_hd = -111,  c_hd = 32000,  d_hd = 33000,  e_hd = -32000;
char format_fhd[]  = "|%hd|%hd|%hd|%hd|%hd|";
char destination_org[250];
char destination_s21[250];
int res_org = sprintf(destination_org,  format_fhd,  a_hd,  b_hd,  c_hd,  d_hd,  e_hd);
int res_s21 = s21_sprintf(destination_s21,  format_fhd,  a_hd,  b_hd,  c_hd,  d_hd,  e_hd);
ck_assert_int_eq(res_s21,  res_org);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_hd2) {
short int a_hd = 0,  b_hd = -111,  c_hd = 32000,  d_hd = 33000,  e_hd = -32000;
char format_fhd[]  = "|%2.1hd|%-5.1hd|% 4.1hd|%+9.hd|%1.1hd|";
char destination_org[250];
char destination_s21[250];
int res_org = sprintf(destination_org,  format_fhd,  a_hd,  b_hd,  c_hd,  d_hd,  e_hd);
int res_s21 = s21_sprintf(destination_s21,  format_fhd,  a_hd,  b_hd,  c_hd,  d_hd,  e_hd);
ck_assert_int_eq(res_s21,  res_org);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST

START_TEST(sprintf_hd3) {
short int a_hd = 12,  b_hd = -111,  c_hd = 32000,  d_hd = 33000,  e_hd = -32000;
char format_fhd[]  = "|%-1.hd|%2.1hd|%1.hd|%4hd|%hd|";
char destination_org[250];
char destination_s21[250];
int res_org = sprintf(destination_org,  format_fhd,  a_hd,  b_hd,  c_hd,  d_hd,  e_hd);
int res_s21 = s21_sprintf(destination_s21,  format_fhd,  a_hd,  b_hd,  c_hd,  d_hd,  e_hd);
ck_assert_int_eq(res_s21,  res_org);
ck_assert_pstr_eq(destination_s21,  destination_org);
}
END_TEST


START_TEST(sprintf_p1) {
int ap = 0, bp = 1, cp = 2, dp = 3;
char format1p[] = "|%#20.5p|%-0.5p|%+020.5p|%-020.5p|";
char destination_org[250];
char destination_s21[250];
int res_org = sprintf(destination_org, format1p, &ap, &bp, &cp, &dp);
s21_sprintf(destination_s21, format1p, &ap, &bp, &cp, &dp);
ck_assert_int_eq(res_org, res_org);
ck_assert_pstr_eq(destination_org, destination_org);
}
END_TEST

START_TEST(sprintf_p2) {
int ap = -1, bp = -12, cp = 12, dp = 10;
char format1p[] = "|% 2.7p|%#0.1p|%010.9p|%08.p|";
char destination_org[250];
char destination_s21[250];
sprintf(destination_org, format1p, &ap, &bp, &cp, &dp);
s21_sprintf(destination_s21, format1p, &ap, &bp, &cp, &dp);
ck_assert_pstr_eq(destination_org, destination_org);
}
END_TEST

START_TEST(sprintf_p3) {
int ap = -1, bp = -12, cp = 12, dp = 10;
char format1p[] = "|% 2.7p|% 0.1p|%-.1p|%-7.p|";
char destination_org[250];
char destination_s21[250];
int res_org = sprintf(destination_org, format1p, &ap, &bp, &cp, &dp);
s21_sprintf(destination_s21, format1p, &ap, &bp, &cp, &dp);
ck_assert_int_eq(res_org, res_org);
ck_assert_pstr_eq(destination_org, destination_org);
// _______________additional_________________
}
END_TEST

// testing inf

START_TEST(sprintf_inf_1) {
char format_float_7[] = "|%-+10.10f|%-+10.15f|%+10f|%-10.0f|";
float var_float_1 = -INFINITY, var_float_2 = INFINITY, var_float_3 = NAN, var_float_4 = NAN;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7,
                        var_float_1, var_float_2, var_float_3, var_float_4);
int res_s21 = s21_sprintf(destination_s21, format_float_7,
                        var_float_1, var_float_2, var_float_3, var_float_4);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

// tests float
START_TEST(sprintf_f_add_1) {
char format_float_7[] = "|%-+10.6f|%-+10.6f|%-+100.7f|%-+100.7f|%-+.8f|%-+.8f|%-+10.12f|%-+10.12f|";
float var_float_1 = 12341234123412341234.15, var_float_2 = -12341234123412341234.15;
char destination_org[500];
char destination_s21[500];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST


START_TEST(sprintf_f_add_2) {
char format_float_7[] = "|%-+10.6f|%-+10.6f|%-+100.7f|%-+100.7f|%-+.8f|%-+.8f|%-+10.12f|%-+10.12f|";
float var_float_1 = 0.9999999, var_float_2 = -0.9999999;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

START_TEST(sprintf_f_add_3) {
char format_float_7[] = "|%-+10.6f|%-+10.6f|%-+100.7f|%-+100.7f|%-+.8f|%-+.8f|%-+10.12f|%-+10.12f|";
float var_float_1 = 1.9999999, var_float_2 = -1.9999999;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

START_TEST(sprintf_f_add_4) {
char format_float_7[] = "|%-+10.6f|%-+10.6f|%-+100.7f|%-+100.7f|%-+.8f|%-+.8f|%-+10.12f|%-+10.12f|";
float var_float_1 = 9.9999999, var_float_2 = -9.9999999;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

START_TEST(sprintf_f_add_10) {
char format_float_7[] = "|%-+10.10f|%-+10.15f|%+11.1f|%-101.5f|";
float var_float_1 = 10.00000000000000000001, var_float_2 = -10.00000000000000000001;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

START_TEST(sprintf_f_add_5) {
char format_float_7[] = "|%-+10.6f|%-+10.6f|%-+100.7f|%-+100.7f|%-+.8f|%-+.8f|%-+10.12f|%-+10.12f|";
float var_float_1 = +000000000000.00000000000000, var_float_2 = -000000000000.00000000000000;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

START_TEST(sprintf_f_add_6) {
char format_float_7[] = "|%-+10.6f|%-+10.6f|%-+100.7f|%-+100.7f|%-+.8f|%-+.8f|%-+10.12f|%-+10.12f|";
float var_float_1 = 0.9999999999999, var_float_2 = -0.9999999999999;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

START_TEST(sprintf_f_add_7) {
char format_float_7[] = "|%-+10.6f|%-+10.6f|%-+100.7f|%-+100.7f|%-+.8f|%-+.8f|%-+10.12f|%-+10.12f|";
float var_float_1 = 1.00000000000001, var_float_2 = -1.0000000000000001;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST


START_TEST(sprintf_f_add_8) {
char format_float_7[] = "|%-+10.6f|%-+10.6f|%-+100.7f|%-+100.7f|%-+.8f|%-+.8f|%-+10.12f|%-+10.12f|";
float var_float_1 = 0.0000000000000001, var_float_2 = -0.000000000000000001;
char destination_org[300];
char destination_s21[300];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

START_TEST(sprintf_f_add_9) {
char format_float_7[] = "|%-+11.0f|%-+1.0f|%-+100.0f|%-+100.0f|%-+.0f|%-+.0f|%-+10.00f|%-+10.00f|";

float var_float_1 = 0, var_float_2 = 0.00000000;
char destination_org[550];
char destination_s21[550];
int res_org = sprintf(destination_org, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
int res_s21 = sprintf(destination_s21, format_float_7, var_float_1, var_float_2,
            var_float_1, var_float_2, var_float_1, var_float_2, var_float_1, var_float_2);
ck_assert_int_eq(res_s21, res_org);
ck_assert_pstr_eq(destination_s21, destination_org);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    // srunner_set_fork_status(sr, CK_NOFORK);

    suite_add_tcase(s1,  tc1_1);
    tcase_add_test(tc1_1,  memchr_1);
    tcase_add_test(tc1_1,  memchr_2);
    tcase_add_test(tc1_1,  memchr_3);
    tcase_add_test(tc1_1,  memchr_4);
    tcase_add_test(tc1_1,  memchr_5);
    tcase_add_test(tc1_1,  memchr_6);
    tcase_add_test(tc1_1,  memcmp_1);
    tcase_add_test(tc1_1,  memcmp_2);
    tcase_add_test(tc1_1,  memcmp_3);
    tcase_add_test(tc1_1,  memcmp_4);
    tcase_add_test(tc1_1,  memcmp_5);
    tcase_add_test(tc1_1,  memcmp_6);
    tcase_add_test(tc1_1,  memcmp_7);
    tcase_add_test(tc1_1,  memcpy_1);
    tcase_add_test(tc1_1,  memcpy_2);
    tcase_add_test(tc1_1,  memcpy_3);
    tcase_add_test(tc1_1,  memcpy_4);
    tcase_add_test(tc1_1,  memcpy_5);
    tcase_add_test(tc1_1,  memmove_1);
    tcase_add_test(tc1_1,  memmove_2);
    tcase_add_test(tc1_1,  memmove_3);
    tcase_add_test(tc1_1,  memmove_4);
    tcase_add_test(tc1_1,  memmove_5);
    tcase_add_test(tc1_1,  memmove_6);
    tcase_add_test(tc1_1,  memset_1);
    tcase_add_test(tc1_1,  memset_2);
    tcase_add_test(tc1_1,  memset_3);
    tcase_add_test(tc1_1,  memset_4);
    tcase_add_test(tc1_1,  memset_5);
    tcase_add_test(tc1_1,  memset_6);
    tcase_add_test(tc1_1,  strcat_1);
    tcase_add_test(tc1_1,  strcat_2);
    tcase_add_test(tc1_1,  strcat_3);
    tcase_add_test(tc1_1,  strcat_4);
    tcase_add_test(tc1_1,  strcat_5);
    tcase_add_test(tc1_1,  strncat_1);
    tcase_add_test(tc1_1,  strncat_2);
    tcase_add_test(tc1_1,  strncat_3);
    tcase_add_test(tc1_1,  strncat_4);
    tcase_add_test(tc1_1,  strncat_5);
    tcase_add_test(tc1_1,  strchr_1);
    tcase_add_test(tc1_1,  strchr_2);
    tcase_add_test(tc1_1,  strchr_3);
    tcase_add_test(tc1_1,  strchr_4);
    tcase_add_test(tc1_1,  strchr_5);
    tcase_add_test(tc1_1,  strcmp_1);
    tcase_add_test(tc1_1,  strcmp_2);
    tcase_add_test(tc1_1,  strcmp_3);
    tcase_add_test(tc1_1,  strcmp_4);
    tcase_add_test(tc1_1,  strcmp_5);
    tcase_add_test(tc1_1,  strncmp_1);
    tcase_add_test(tc1_1,  strncmp_2);
    tcase_add_test(tc1_1,  strncmp_3);
    tcase_add_test(tc1_1,  strncmp_4);
    tcase_add_test(tc1_1,  strncmp_5);
    tcase_add_test(tc1_1,  strncmp_6);
    tcase_add_test(tc1_1,  strcpy_1);
    tcase_add_test(tc1_1,  strcpy_2);
    tcase_add_test(tc1_1,  strcpy_3);
    tcase_add_test(tc1_1,  strcpy_4);
    tcase_add_test(tc1_1,  strcpy_5);
    tcase_add_test(tc1_1,  strncpy_1);
    tcase_add_test(tc1_1,  strncpy_2);
    tcase_add_test(tc1_1,  strncpy_3);
    tcase_add_test(tc1_1,  strncpy_4);
    tcase_add_test(tc1_1,  strncpy_5);
    tcase_add_test(tc1_1,  strcspn_1);
    tcase_add_test(tc1_1,  strcspn_2);
    tcase_add_test(tc1_1,  strcspn_3);
    tcase_add_test(tc1_1,  strcspn_4);
    tcase_add_test(tc1_1,  strcspn_5);
    tcase_add_test(tc1_1,  strcspn_6);
    tcase_add_test(tc1_1,  strerror_1);
    tcase_add_test(tc1_1,  strerror_2);
    tcase_add_test(tc1_1,  strerror_3);
    tcase_add_test(tc1_1,  strerror_4);
    tcase_add_test(tc1_1,  strerror_5);
    tcase_add_test(tc1_1,  strlen_1);
    tcase_add_test(tc1_1,  strlen_2);
    tcase_add_test(tc1_1,  strlen_3);
    tcase_add_test(tc1_1,  strpbrk_1);
    tcase_add_test(tc1_1,  strpbrk_2);
    tcase_add_test(tc1_1,  strpbrk_3);
    tcase_add_test(tc1_1,  strpbrk_4);
    tcase_add_test(tc1_1,  strpbrk_6);
    tcase_add_test(tc1_1,  strrchr_1);
    tcase_add_test(tc1_1,  strrchr_2);
    tcase_add_test(tc1_1,  strrchr_3);
    tcase_add_test(tc1_1,  strrchr_4);
    tcase_add_test(tc1_1,  strrchr_6);
    tcase_add_test(tc1_1,  strspn_1);
    tcase_add_test(tc1_1,  strspn_2);
    tcase_add_test(tc1_1,  strspn_3);
    tcase_add_test(tc1_1,  strspn_4);
    tcase_add_test(tc1_1,  strspn_5);
    tcase_add_test(tc1_1,  strspn_6);
    tcase_add_test(tc1_1,  strstr_1);
    tcase_add_test(tc1_1,  strstr_2);
    tcase_add_test(tc1_1,  strstr_3);
    tcase_add_test(tc1_1,  strstr_4);
    tcase_add_test(tc1_1,  strstr_5);
    tcase_add_test(tc1_1,  strstr_6);
    tcase_add_test(tc1_1,  strtok_1);
    tcase_add_test(tc1_1,  strtok_2);
    tcase_add_test(tc1_1,  strtok_3);
    tcase_add_test(tc1_1,  strtok_4);
    tcase_add_test(tc1_1,  strtok_5);
    tcase_add_test(tc1_1,  to_upper_1);
    tcase_add_test(tc1_1,  to_upper_2);
    tcase_add_test(tc1_1,  to_upper_3);
    tcase_add_test(tc1_1,  to_upper_4);
    tcase_add_test(tc1_1,  to_upper_5);
    tcase_add_test(tc1_1,  to_upper_6);
    tcase_add_test(tc1_1,  to_upper_7);
    tcase_add_test(tc1_1,  to_upper_8);
    tcase_add_test(tc1_1,  to_lower_1);
    tcase_add_test(tc1_1,  to_lower_2);
    tcase_add_test(tc1_1,  to_lower_3);
    tcase_add_test(tc1_1,  to_lower_4);
    tcase_add_test(tc1_1,  to_lower_5);
    tcase_add_test(tc1_1,  to_lower_6);
    tcase_add_test(tc1_1,  to_lower_7);
    tcase_add_test(tc1_1,  insert_1);
    tcase_add_test(tc1_1,  insert_2);
    tcase_add_test(tc1_1,  insert_4);
    tcase_add_test(tc1_1,  insert_5);
    tcase_add_test(tc1_1,  insert_6);
    tcase_add_test(tc1_1,  trim_1);
    tcase_add_test(tc1_1,  trim_2);
    tcase_add_test(tc1_1,  trim_3);
    tcase_add_test(tc1_1,  trim_4);
    tcase_add_test(tc1_1,  trim_5);
    tcase_add_test(tc1_1,  trim_6);
    tcase_add_test(tc1_1,  trim_7);
    tcase_add_test(tc1_1,  trim_8);
    tcase_add_test(tc1_1,  trim_10);
    tcase_add_test(tc1_1,  sprintf_1);
    tcase_add_test(tc1_1,  sprintf_e2);
    tcase_add_test(tc1_1,  sprintf_e3);
    tcase_add_test(tc1_1,  sprintf_e4);
    tcase_add_test(tc1_1,  sprintf_d3);
    tcase_add_test(tc1_1,  sprintf_d4);
    tcase_add_test(tc1_1,  sprintf_d5);
    tcase_add_test(tc1_1,  sprintf_f1);
    tcase_add_test(tc1_1,  sprintf_f2);
    tcase_add_test(tc1_1,  sprintf_f3);
    tcase_add_test(tc1_1,  sprintf_f4);
    tcase_add_test(tc1_1,  sprintf_c1);
    tcase_add_test(tc1_1,  sprintf_c2);
    tcase_add_test(tc1_1,  sprintf_c3);
    tcase_add_test(tc1_1,  sprintf_s1);
    tcase_add_test(tc1_1,  sprintf_s2);
    tcase_add_test(tc1_1,  sprintf_s3);
    tcase_add_test(tc1_1,  sprintf_s4);
    tcase_add_test(tc1_1,  sprintf_s5);
    tcase_add_test(tc1_1,  sprintf_u1);
    tcase_add_test(tc1_1,  sprintf_u2);
    tcase_add_test(tc1_1,  sprintf_u3);
    tcase_add_test(tc1_1,  sprintf_hd1);
    tcase_add_test(tc1_1,  sprintf_hd2);
    tcase_add_test(tc1_1,  sprintf_hd3);
    tcase_add_test(tc1_1, sprintf_p1);
    tcase_add_test(tc1_1, sprintf_p2);
    tcase_add_test(tc1_1, sprintf_p3);
    tcase_add_test(tc1_1, sprintf_inf_1);
    tcase_add_test(tc1_1, sprintf_f_add_1);
    tcase_add_test(tc1_1, sprintf_f_add_2);
    tcase_add_test(tc1_1, sprintf_f_add_3);
    tcase_add_test(tc1_1, sprintf_f_add_4);
    tcase_add_test(tc1_1, sprintf_f_add_5);
    tcase_add_test(tc1_1, sprintf_f_add_6);
    tcase_add_test(tc1_1, sprintf_f_add_7);
    tcase_add_test(tc1_1, sprintf_f_add_8);
    tcase_add_test(tc1_1, sprintf_f_add_9);
    tcase_add_test(tc1_1, sprintf_f_add_10);
    srunner_run_all(sr,  CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);
    return nf == 0 ? 0 : 1;
}
